const constants = {
	FOCUS: "FOCUS",
	BLUR: "BLUR",
	OK: "OK",
	CANCEL: "CANCEL",
	SHOW: "SHOW",
	DATE_SELECTED: "DATE_SELECTED",
	DATE_RANGE_CHANGE: "DATE_RANGE_CHANGE",
	DATE_RANGE_DEFAULT: "DATE_RANGE_DEFAULT",
	CALENDAR_HIDE: "CALENDAR_HIDE",
	SUBMIT_CLICK: "SUBMIT_CLICK",
	INIT: "INIT",
	ARROW_CLICK: "ARROW_CLICK"
};

export default constants;
